config/routes.rb
Rails.application.routes.draw do
  root 'countdowns#index'
  resources :countdowns
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/countdown.rb
class Countdown < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countdowns_controller.rb
class CountdownsController < ApplicationController
  before_action :set_countdown, only: %i[ show edit update destroy ]

  # GET /countdowns or /countdowns.json
  def index
    @countdowns = Countdown.all
  end

  # GET /countdowns/1 or /countdowns/1.json
  def show
  end

  # GET /countdowns/new
  def new
    @countdown = Countdown.new
  end

  # GET /countdowns/1/edit
  def edit
  end

  # POST /countdowns or /countdowns.json
  def create
    @countdown = Countdown.new(countdown_params)

    respond_to do |format|
      if @countdown.save
        format.html { redirect_to countdown_url(@countdown), notice: "Countdown was successfully created." }
        format.json { render :show, status: :created, location: @countdown }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @countdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countdowns/1 or /countdowns/1.json
  def update
    respond_to do |format|
      if @countdown.update(countdown_params)
        format.html { redirect_to countdown_url(@countdown), notice: "Countdown was successfully updated." }
        format.json { render :show, status: :ok, location: @countdown }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @countdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countdowns/1 or /countdowns/1.json
  def destroy
    @countdown.destroy!

    respond_to do |format|
      format.html { redirect_to countdowns_url, notice: "Countdown was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_countdown
      @countdown = Countdown.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def countdown_params
      params.require(:countdown).permit(:name, :description, :target)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countdowns_helper.rb
module CountdownsHelper
end

app/views/countdowns/_countdown.html.erb
<div id="<%= dom_id countdown %>">
  <p>
    <strong>Name:</strong>
    <%= countdown.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= countdown.description %>
  </p>

  <p>
    <strong>Target:</strong>
    <%= countdown.target %>
  </p>

  <% seconds_until_target_time = countdown.target.to_i - Time.now.to_i %>

  <%= content_tag(:h1, "", data: {
    controller: "countdown",
    countdown_target: "countdown",
    seconds_until_end_value: seconds_until_target_time
  }) %>


</div>

app/views/countdowns/_form.html.erb
<%= form_with(model: countdown) do |form| %>
  <% if countdown.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(countdown.errors.count, "error") %> prohibited this countdown from being saved:</h2>

      <ul>
        <% countdown.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :target, style: "display: block" %>
    <%= form.datetime_field :target %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countdowns/edit.html.erb
<h1>Editing countdown</h1>

<%= render "form", countdown: @countdown %>

<br>

<div>
  <%= link_to "Show this countdown", @countdown %> |
  <%= link_to "Back to countdowns", countdowns_path %>
</div>

app/views/countdowns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Countdowns</h1>

<div id="countdowns">
  <% @countdowns.each do |countdown| %>
    <%= render countdown %>
    <p>
      <%= link_to "Show this countdown", countdown %>
    </p>
  <% end %>
</div>

<%= link_to "New countdown", new_countdown_path %>

app/views/countdowns/new.html.erb
<h1>New countdown</h1>

<%= render "form", countdown: @countdown %>

<br>

<div>
  <%= link_to "Back to countdowns", countdowns_path %>
</div>

app/views/countdowns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @countdown %>

<div>
  <%= link_to "Edit this countdown", edit_countdown_path(@countdown) %> |
  <%= link_to "Back to countdowns", countdowns_path %>

  <%= button_to "Destroy this countdown", @countdown, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails7NyCountdown</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>